### ISSUE TITLE
Logging of finished jobs

### ISSUE THREAD

**Issue by martin-ro** [cyppe/laravel-batch-jobs-redis-driver#1]
I know this is a wip but should at least the Log for finished batches be removed?

And thanks for the package, I already use it in production and it took a great deal of pressure from my server!

https://github.com/cyppe/laravel-batch-jobs-redis-driver/blob/6db8d35e106b61529ab87ed01f09a8eb3564efd5/src/Repositories/RedisBatchRepository.php#L219

**Comment by cyppe** [comment]
Hi!

Glad to hear my package was helpful. I built it out of my own frustrations :-)

Totally agree with you on the logs.

In today's release, they're turned off by default. But they can be turned back on if someone notices any issues with batches. 

It can be really helpful to enable debug logs and attach the output in case someone notices any issue and opens issue.
